---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

This is a line from Rstudio
This is a line from RStudio
This is a line from RStudio
This is a line from Rstudio

### step 12.1
- Praneet's note: No problems, already had git and github setup and know how to use git operations
- Grace's note: Had to download Github to my computer and had some issues with that. 
- Lyn (Kalyna)'s note: Git was already installed, no problems.


### step 12.2
- Praneet's note: Repository was given to us
- Grace's note: Repository was already giveb to us
- Lyn's note: See above


### step 12.3
- Praneet's note: Had no problems cloning the repository onto my laptop 
- Lyn's note: No problems cloning


### step 12.4
- Praneet's note: Had no problems making local changes and commiting
- Grace's note: Had a lot of questions about cloning since this was my first time using Github. I feel like I have a better understanding now. 
- Lyn's note: No problems committing and making changes

### step 12.5
- Praneet's note: Had no problems pushing onto Github
- Grace's note: Had no real problems pushing into Github
- Lyn's note: Had an issue with the Git Token, but was able to fix it with instructor help


### step 12.6
- Praneet's note: The local changes and commits were synced with the Github remote
- Grace's note: The local changed were sycned with Github
- Lyn's note: No issues syncing with github











